### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by andersy005**
- Add PyPI and Conda badges
- Add installation instructions

### CODE REVIEW

**Comment by bradyrx** [comment]
Given the inclusion of conda/PyPI is this package in a working format now? I just came across a problem where I'd like to remap onto isopycnals but wasn't sure where this was in development.

**Comment by roxyboy** [comment]
@bradyrx I've been using it for a few months now but it works fine for my purposes :)

**Comment by bradyrx** [comment]
@roxyboy, awesome. Do you have any gists or example notebooks? It would be good to get a readthedocs going here with an API, examples, etc.!

**Comment by roxyboy** [comment]
The notebook: https://github.com/cspencerjones/xlayers/blob/master/notebooks/Test_Packaging.ipynb would probably suffice to get you started as it pulls publicly available data but I agree it would be nice if we could get a readthedocs going. The data for the cases I've been using `xlayers` isn't publicly available...

**Pull request merged**
